. "$PSScriptRoot/IOPathStructureWindowsRule.ps1"
. "$PSScriptRoot/IOPathStructureLinuxRule.ps1"
. "$PSScriptRoot/IOPathStructureMacOSRule.ps1"
. "$PSScriptRoot/IOPathSyntaxWindowsRule.ps1"
. "$PSScriptRoot/IOPathSyntaxLinuxRule.ps1"
. "$PSScriptRoot/IOPathSyntaxMacOSRule.ps1"