# . "$([System.IO.Path]::Join($PSScriptRoot, 'PublicErrorId.ps1'))"
# . "$([System.IO.Path]::Join($PSScriptRoot, 'ErrorIdResolver.ps1'))"
# . "$([System.IO.Path]::Join($PSScriptRoot, 'ErrorCategoryResolver.ps1'))"
# . "$([System.IO.Path]::Join($PSScriptRoot, 'ApplicationExceptionErrorRecordTranslator.ps1'))"
. "$([System.IO.Path]::Join($PSScriptRoot, 'ErrorRecordFactory.ps1'))"
. "$([System.IO.Path]::Join($PSScriptRoot, 'ArgumentErrorDiagnosticFormatter.ps1'))"